from .mainwindow import Ui_MainWindow
from .variationsettings import Ui_VariationSettingsWindow
from .modifiersettings import Ui_ModifierSettingsWindow
from .modifiercombinationsdialog import Ui_CombinationsDialog