# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\gui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblInput = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInput.sizePolicy().hasHeightForWidth())
        self.lblInput.setSizePolicy(sizePolicy)
        self.lblInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.lblInput.setObjectName("lblInput")
        self.horizontalLayout_2.addWidget(self.lblInput)
        self.txtInputFile = QtWidgets.QLineEdit(self.centralwidget)
        self.txtInputFile.setReadOnly(True)
        self.txtInputFile.setObjectName("txtInputFile")
        self.horizontalLayout_2.addWidget(self.txtInputFile)
        self.btnBrowseInput = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowseInput.setCheckable(False)
        self.btnBrowseInput.setObjectName("btnBrowseInput")
        self.horizontalLayout_2.addWidget(self.btnBrowseInput)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.gvLoadedImage = QtWidgets.QGraphicsView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gvLoadedImage.sizePolicy().hasHeightForWidth())
        self.gvLoadedImage.setSizePolicy(sizePolicy)
        self.gvLoadedImage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gvLoadedImage.setObjectName("gvLoadedImage")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeLayers = QtWidgets.QTreeView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeLayers.sizePolicy().hasHeightForWidth())
        self.treeLayers.setSizePolicy(sizePolicy)
        self.treeLayers.setMinimumSize(QtCore.QSize(200, 0))
        self.treeLayers.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeLayers.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeLayers.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.treeLayers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeLayers.setProperty("showDropIndicator", False)
        self.treeLayers.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.treeLayers.setObjectName("treeLayers")
        self.verticalLayout.addWidget(self.treeLayers)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnResetLayers = QtWidgets.QPushButton(self.layoutWidget)
        self.btnResetLayers.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResetLayers.sizePolicy().hasHeightForWidth())
        self.btnResetLayers.setSizePolicy(sizePolicy)
        self.btnResetLayers.setObjectName("btnResetLayers")
        self.horizontalLayout_3.addWidget(self.btnResetLayers)
        self.btnUpdatePreview = QtWidgets.QPushButton(self.layoutWidget)
        self.btnUpdatePreview.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUpdatePreview.sizePolicy().hasHeightForWidth())
        self.btnUpdatePreview.setSizePolicy(sizePolicy)
        self.btnUpdatePreview.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnUpdatePreview.setObjectName("btnUpdatePreview")
        self.horizontalLayout_3.addWidget(self.btnUpdatePreview)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblOutput = QtWidgets.QLabel(self.centralwidget)
        self.lblOutput.setObjectName("lblOutput")
        self.horizontalLayout.addWidget(self.lblOutput)
        self.txtOutputDir = QtWidgets.QLineEdit(self.centralwidget)
        self.txtOutputDir.setReadOnly(True)
        self.txtOutputDir.setObjectName("txtOutputDir")
        self.horizontalLayout.addWidget(self.txtOutputDir)
        self.btnBrowseOutputDir = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowseOutputDir.setObjectName("btnBrowseOutputDir")
        self.horizontalLayout.addWidget(self.btnBrowseOutputDir)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStart.sizePolicy().hasHeightForWidth())
        self.btnStart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName("btnStart")
        self.verticalLayout_2.addWidget(self.btnStart, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        self.menuVariations = QtWidgets.QMenu(self.menubar)
        self.menuVariations.setObjectName("menuVariations")
        self.menuModifiers = QtWidgets.QMenu(self.menubar)
        self.menuModifiers.setObjectName("menuModifiers")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAddNewVariation = QtWidgets.QAction(MainWindow)
        self.actionAddNewVariation.setObjectName("actionAddNewVariation")
        self.actionAddNewModifier = QtWidgets.QAction(MainWindow)
        self.actionAddNewModifier.setObjectName("actionAddNewModifier")
        self.menuVariations.addAction(self.actionAddNewVariation)
        self.menuModifiers.addAction(self.actionAddNewModifier)
        self.menubar.addAction(self.menuVariations.menuAction())
        self.menubar.addAction(self.menuModifiers.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ILLustration Variations Exporter"))
        self.lblInput.setText(_translate("MainWindow", "Input:"))
        self.btnBrowseInput.setText(_translate("MainWindow", "Browse..."))
        self.btnResetLayers.setText(_translate("MainWindow", "Reset"))
        self.btnUpdatePreview.setText(_translate("MainWindow", "Update preview"))
        self.lblOutput.setText(_translate("MainWindow", "Output:"))
        self.btnBrowseOutputDir.setText(_translate("MainWindow", "Browse..."))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.menuVariations.setTitle(_translate("MainWindow", "Variations"))
        self.menuModifiers.setTitle(_translate("MainWindow", "Modifiers"))
        self.actionAddNewVariation.setText(_translate("MainWindow", "Add new ..."))
        self.actionAddNewModifier.setText(_translate("MainWindow", "Add new..."))

