# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\gui\modifiersettings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ModifierSettingsWindow(object):
    def setupUi(self, ModifierSettingsWindow):
        ModifierSettingsWindow.setObjectName("ModifierSettingsWindow")
        ModifierSettingsWindow.resize(720, 308)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../res/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ModifierSettingsWindow.setWindowIcon(icon)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(ModifierSettingsWindow)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblName = QtWidgets.QLabel(ModifierSettingsWindow)
        self.lblName.setObjectName("lblName")
        self.horizontalLayout.addWidget(self.lblName)
        self.txtName = QtWidgets.QLineEdit(ModifierSettingsWindow)
        self.txtName.setText("")
        self.txtName.setObjectName("txtName")
        self.horizontalLayout.addWidget(self.txtName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblSuffix = QtWidgets.QLabel(ModifierSettingsWindow)
        self.lblSuffix.setObjectName("lblSuffix")
        self.horizontalLayout_2.addWidget(self.lblSuffix)
        self.txtSuffix = QtWidgets.QLineEdit(ModifierSettingsWindow)
        self.txtSuffix.setText("")
        self.txtSuffix.setObjectName("txtSuffix")
        self.horizontalLayout_2.addWidget(self.txtSuffix)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblInclusions = QtWidgets.QLabel(ModifierSettingsWindow)
        self.lblInclusions.setObjectName("lblInclusions")
        self.verticalLayout.addWidget(self.lblInclusions)
        self.lvInclusions = QtWidgets.QListView(ModifierSettingsWindow)
        self.lvInclusions.setObjectName("lvInclusions")
        self.verticalLayout.addWidget(self.lvInclusions)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbInclusionPattType = QtWidgets.QComboBox(ModifierSettingsWindow)
        self.cbInclusionPattType.setObjectName("cbInclusionPattType")
        self.cbInclusionPattType.addItem("")
        self.cbInclusionPattType.addItem("")
        self.horizontalLayout_4.addWidget(self.cbInclusionPattType)
        self.txtInclusionPatt = QtWidgets.QLineEdit(ModifierSettingsWindow)
        self.txtInclusionPatt.setText("")
        self.txtInclusionPatt.setObjectName("txtInclusionPatt")
        self.horizontalLayout_4.addWidget(self.txtInclusionPatt)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnAddInclusion = QtWidgets.QPushButton(ModifierSettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddInclusion.sizePolicy().hasHeightForWidth())
        self.btnAddInclusion.setSizePolicy(sizePolicy)
        self.btnAddInclusion.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnAddInclusion.setObjectName("btnAddInclusion")
        self.horizontalLayout_5.addWidget(self.btnAddInclusion)
        self.btnRemoveInclusion = QtWidgets.QPushButton(ModifierSettingsWindow)
        self.btnRemoveInclusion.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemoveInclusion.sizePolicy().hasHeightForWidth())
        self.btnRemoveInclusion.setSizePolicy(sizePolicy)
        self.btnRemoveInclusion.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnRemoveInclusion.setObjectName("btnRemoveInclusion")
        self.horizontalLayout_5.addWidget(self.btnRemoveInclusion)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblExclusions = QtWidgets.QLabel(ModifierSettingsWindow)
        self.lblExclusions.setObjectName("lblExclusions")
        self.verticalLayout_2.addWidget(self.lblExclusions)
        self.lvExclusions = QtWidgets.QListView(ModifierSettingsWindow)
        self.lvExclusions.setObjectName("lvExclusions")
        self.verticalLayout_2.addWidget(self.lvExclusions)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cbExclusionPattType = QtWidgets.QComboBox(ModifierSettingsWindow)
        self.cbExclusionPattType.setObjectName("cbExclusionPattType")
        self.cbExclusionPattType.addItem("")
        self.cbExclusionPattType.addItem("")
        self.horizontalLayout_7.addWidget(self.cbExclusionPattType)
        self.txtExclusionPatt = QtWidgets.QLineEdit(ModifierSettingsWindow)
        self.txtExclusionPatt.setText("")
        self.txtExclusionPatt.setObjectName("txtExclusionPatt")
        self.horizontalLayout_7.addWidget(self.txtExclusionPatt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnAddExclusion = QtWidgets.QPushButton(ModifierSettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddExclusion.sizePolicy().hasHeightForWidth())
        self.btnAddExclusion.setSizePolicy(sizePolicy)
        self.btnAddExclusion.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnAddExclusion.setObjectName("btnAddExclusion")
        self.horizontalLayout_8.addWidget(self.btnAddExclusion)
        self.btnRemoveExclusion = QtWidgets.QPushButton(ModifierSettingsWindow)
        self.btnRemoveExclusion.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemoveExclusion.sizePolicy().hasHeightForWidth())
        self.btnRemoveExclusion.setSizePolicy(sizePolicy)
        self.btnRemoveExclusion.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnRemoveExclusion.setObjectName("btnRemoveExclusion")
        self.horizontalLayout_8.addWidget(self.btnRemoveExclusion)
        spacerItem4 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.horizontalLayout_8.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.btnSave = QtWidgets.QPushButton(ModifierSettingsWindow)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_12.addWidget(self.btnSave)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)

        self.retranslateUi(ModifierSettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(ModifierSettingsWindow)

    def retranslateUi(self, ModifierSettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        ModifierSettingsWindow.setWindowTitle(_translate("ModifierSettingsWindow", "Modifier Settings"))
        self.lblName.setText(_translate("ModifierSettingsWindow", "Name"))
        self.lblSuffix.setText(_translate("ModifierSettingsWindow", "Suffix"))
        self.lblInclusions.setText(_translate("ModifierSettingsWindow", "Inclusion Patterns"))
        self.cbInclusionPattType.setItemText(0, _translate("ModifierSettingsWindow", "glob"))
        self.cbInclusionPattType.setItemText(1, _translate("ModifierSettingsWindow", "regex"))
        self.txtInclusionPatt.setPlaceholderText(_translate("ModifierSettingsWindow", "Type here the pattern to add..."))
        self.btnAddInclusion.setText(_translate("ModifierSettingsWindow", "+"))
        self.btnRemoveInclusion.setText(_translate("ModifierSettingsWindow", "-"))
        self.lblExclusions.setText(_translate("ModifierSettingsWindow", "Exclusion Patterns"))
        self.cbExclusionPattType.setItemText(0, _translate("ModifierSettingsWindow", "glob"))
        self.cbExclusionPattType.setItemText(1, _translate("ModifierSettingsWindow", "regex"))
        self.txtExclusionPatt.setPlaceholderText(_translate("ModifierSettingsWindow", "Type here the pattern to add..."))
        self.btnAddExclusion.setText(_translate("ModifierSettingsWindow", "+"))
        self.btnRemoveExclusion.setText(_translate("ModifierSettingsWindow", "-"))
        self.btnSave.setText(_translate("ModifierSettingsWindow", "Save"))

