# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\gui\variationsettings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VariationSettingsWindow(object):
    def setupUi(self, VariationSettingsWindow):
        VariationSettingsWindow.setObjectName("VariationSettingsWindow")
        VariationSettingsWindow.resize(720, 650)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(VariationSettingsWindow)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblName = QtWidgets.QLabel(VariationSettingsWindow)
        self.lblName.setObjectName("lblName")
        self.horizontalLayout.addWidget(self.lblName)
        self.txtName = QtWidgets.QLineEdit(VariationSettingsWindow)
        self.txtName.setText("")
        self.txtName.setObjectName("txtName")
        self.horizontalLayout.addWidget(self.txtName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblSuffix = QtWidgets.QLabel(VariationSettingsWindow)
        self.lblSuffix.setObjectName("lblSuffix")
        self.horizontalLayout_2.addWidget(self.lblSuffix)
        self.txtSuffix = QtWidgets.QLineEdit(VariationSettingsWindow)
        self.txtSuffix.setText("")
        self.txtSuffix.setObjectName("txtSuffix")
        self.horizontalLayout_2.addWidget(self.txtSuffix)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblSubfolder = QtWidgets.QLabel(VariationSettingsWindow)
        self.lblSubfolder.setObjectName("lblSubfolder")
        self.horizontalLayout_3.addWidget(self.lblSubfolder)
        self.txtSubfolder = QtWidgets.QLineEdit(VariationSettingsWindow)
        self.txtSubfolder.setText("")
        self.txtSubfolder.setObjectName("txtSubfolder")
        self.horizontalLayout_3.addWidget(self.txtSubfolder)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblInclusions = QtWidgets.QLabel(VariationSettingsWindow)
        self.lblInclusions.setObjectName("lblInclusions")
        self.verticalLayout.addWidget(self.lblInclusions)
        self.lvInclusions = QtWidgets.QListView(VariationSettingsWindow)
        self.lvInclusions.setObjectName("lvInclusions")
        self.verticalLayout.addWidget(self.lvInclusions)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbInclusionPattType = QtWidgets.QComboBox(VariationSettingsWindow)
        self.cbInclusionPattType.setObjectName("cbInclusionPattType")
        self.cbInclusionPattType.addItem("")
        self.cbInclusionPattType.setItemText(0, "glob")
        self.cbInclusionPattType.addItem("")
        self.cbInclusionPattType.setItemText(1, "regex")
        self.horizontalLayout_4.addWidget(self.cbInclusionPattType)
        self.txtInclusionPatt = QtWidgets.QLineEdit(VariationSettingsWindow)
        self.txtInclusionPatt.setText("")
        self.txtInclusionPatt.setObjectName("txtInclusionPatt")
        self.horizontalLayout_4.addWidget(self.txtInclusionPatt)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnAddInclusion = QtWidgets.QPushButton(VariationSettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddInclusion.sizePolicy().hasHeightForWidth())
        self.btnAddInclusion.setSizePolicy(sizePolicy)
        self.btnAddInclusion.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnAddInclusion.setObjectName("btnAddInclusion")
        self.horizontalLayout_5.addWidget(self.btnAddInclusion)
        self.btnRemoveInclusion = QtWidgets.QPushButton(VariationSettingsWindow)
        self.btnRemoveInclusion.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemoveInclusion.sizePolicy().hasHeightForWidth())
        self.btnRemoveInclusion.setSizePolicy(sizePolicy)
        self.btnRemoveInclusion.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnRemoveInclusion.setObjectName("btnRemoveInclusion")
        self.horizontalLayout_5.addWidget(self.btnRemoveInclusion)
        spacerItem3 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblExclusions = QtWidgets.QLabel(VariationSettingsWindow)
        self.lblExclusions.setObjectName("lblExclusions")
        self.verticalLayout_2.addWidget(self.lblExclusions)
        self.lvExclusions = QtWidgets.QListView(VariationSettingsWindow)
        self.lvExclusions.setObjectName("lvExclusions")
        self.verticalLayout_2.addWidget(self.lvExclusions)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cbExclusionPattType = QtWidgets.QComboBox(VariationSettingsWindow)
        self.cbExclusionPattType.setObjectName("cbExclusionPattType")
        self.cbExclusionPattType.addItem("")
        self.cbExclusionPattType.addItem("")
        self.horizontalLayout_7.addWidget(self.cbExclusionPattType)
        self.txtExclusionPatt = QtWidgets.QLineEdit(VariationSettingsWindow)
        self.txtExclusionPatt.setText("")
        self.txtExclusionPatt.setObjectName("txtExclusionPatt")
        self.horizontalLayout_7.addWidget(self.txtExclusionPatt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnAddExclusion = QtWidgets.QPushButton(VariationSettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddExclusion.sizePolicy().hasHeightForWidth())
        self.btnAddExclusion.setSizePolicy(sizePolicy)
        self.btnAddExclusion.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnAddExclusion.setObjectName("btnAddExclusion")
        self.horizontalLayout_8.addWidget(self.btnAddExclusion)
        self.btnRemoveExclusion = QtWidgets.QPushButton(VariationSettingsWindow)
        self.btnRemoveExclusion.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemoveExclusion.sizePolicy().hasHeightForWidth())
        self.btnRemoveExclusion.setSizePolicy(sizePolicy)
        self.btnRemoveExclusion.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnRemoveExclusion.setObjectName("btnRemoveExclusion")
        self.horizontalLayout_8.addWidget(self.btnRemoveExclusion)
        spacerItem5 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.horizontalLayout_8.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblLinkedModifiers = QtWidgets.QLabel(VariationSettingsWindow)
        self.lblLinkedModifiers.setObjectName("lblLinkedModifiers")
        self.verticalLayout_3.addWidget(self.lblLinkedModifiers)
        self.tvLinkedModifiers = QtWidgets.QTreeView(VariationSettingsWindow)
        self.tvLinkedModifiers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvLinkedModifiers.setObjectName("tvLinkedModifiers")
        self.verticalLayout_3.addWidget(self.tvLinkedModifiers)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnMoveModUp = QtWidgets.QPushButton(VariationSettingsWindow)
        self.btnMoveModUp.setEnabled(False)
        self.btnMoveModUp.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnMoveModUp.setObjectName("btnMoveModUp")
        self.horizontalLayout_9.addWidget(self.btnMoveModUp)
        self.btnMoveModDown = QtWidgets.QPushButton(VariationSettingsWindow)
        self.btnMoveModDown.setEnabled(False)
        self.btnMoveModDown.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnMoveModDown.setObjectName("btnMoveModDown")
        self.horizontalLayout_9.addWidget(self.btnMoveModDown)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.btnLinkAllModifiers = QtWidgets.QPushButton(VariationSettingsWindow)
        self.btnLinkAllModifiers.setEnabled(False)
        self.btnLinkAllModifiers.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnLinkAllModifiers.setObjectName("btnLinkAllModifiers")
        self.verticalLayout_5.addWidget(self.btnLinkAllModifiers)
        self.btnLinkModifier = QtWidgets.QPushButton(VariationSettingsWindow)
        self.btnLinkModifier.setEnabled(False)
        self.btnLinkModifier.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnLinkModifier.setObjectName("btnLinkModifier")
        self.verticalLayout_5.addWidget(self.btnLinkModifier)
        self.btnUnlinkModifier = QtWidgets.QPushButton(VariationSettingsWindow)
        self.btnUnlinkModifier.setEnabled(False)
        self.btnUnlinkModifier.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnUnlinkModifier.setObjectName("btnUnlinkModifier")
        self.verticalLayout_5.addWidget(self.btnUnlinkModifier)
        self.btnUnlinkAllModifiers = QtWidgets.QPushButton(VariationSettingsWindow)
        self.btnUnlinkAllModifiers.setEnabled(False)
        self.btnUnlinkAllModifiers.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnUnlinkAllModifiers.setObjectName("btnUnlinkAllModifiers")
        self.verticalLayout_5.addWidget(self.btnUnlinkAllModifiers)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblAvailableModifiers = QtWidgets.QLabel(VariationSettingsWindow)
        self.lblAvailableModifiers.setObjectName("lblAvailableModifiers")
        self.verticalLayout_4.addWidget(self.lblAvailableModifiers)
        self.tvAvailableModifiers = QtWidgets.QTreeView(VariationSettingsWindow)
        self.tvAvailableModifiers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvAvailableModifiers.setObjectName("tvAvailableModifiers")
        self.verticalLayout_4.addWidget(self.tvAvailableModifiers)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.btnSave = QtWidgets.QPushButton(VariationSettingsWindow)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_12.addWidget(self.btnSave)
        self.btnConfigureCombinations = QtWidgets.QPushButton(VariationSettingsWindow)
        self.btnConfigureCombinations.setEnabled(False)
        self.btnConfigureCombinations.setObjectName("btnConfigureCombinations")
        self.horizontalLayout_12.addWidget(self.btnConfigureCombinations)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)

        self.retranslateUi(VariationSettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(VariationSettingsWindow)

    def retranslateUi(self, VariationSettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        VariationSettingsWindow.setWindowTitle(_translate("VariationSettingsWindow", "Variation Settings"))
        self.lblName.setText(_translate("VariationSettingsWindow", "Name"))
        self.lblSuffix.setText(_translate("VariationSettingsWindow", "Suffix"))
        self.lblSubfolder.setText(_translate("VariationSettingsWindow", "Subfolder Name"))
        self.lblInclusions.setText(_translate("VariationSettingsWindow", "Inclusion Patterns"))
        self.txtInclusionPatt.setPlaceholderText(_translate("VariationSettingsWindow", "Type here the pattern to add..."))
        self.btnAddInclusion.setText(_translate("VariationSettingsWindow", "+"))
        self.btnRemoveInclusion.setText(_translate("VariationSettingsWindow", "-"))
        self.lblExclusions.setText(_translate("VariationSettingsWindow", "Exclusion Patterns"))
        self.cbExclusionPattType.setItemText(0, _translate("VariationSettingsWindow", "glob"))
        self.cbExclusionPattType.setItemText(1, _translate("VariationSettingsWindow", "regex"))
        self.txtExclusionPatt.setPlaceholderText(_translate("VariationSettingsWindow", "Type here the pattern to add..."))
        self.btnAddExclusion.setText(_translate("VariationSettingsWindow", "+"))
        self.btnRemoveExclusion.setText(_translate("VariationSettingsWindow", "-"))
        self.lblLinkedModifiers.setText(_translate("VariationSettingsWindow", "Linked Modifiers"))
        self.btnMoveModUp.setText(_translate("VariationSettingsWindow", "˄"))
        self.btnMoveModDown.setText(_translate("VariationSettingsWindow", "˅"))
        self.btnLinkAllModifiers.setText(_translate("VariationSettingsWindow", "<<"))
        self.btnLinkModifier.setText(_translate("VariationSettingsWindow", "<"))
        self.btnUnlinkModifier.setText(_translate("VariationSettingsWindow", ">"))
        self.btnUnlinkAllModifiers.setText(_translate("VariationSettingsWindow", ">>"))
        self.lblAvailableModifiers.setText(_translate("VariationSettingsWindow", "Available Modifiers"))
        self.btnSave.setText(_translate("VariationSettingsWindow", "Save"))
        self.btnConfigureCombinations.setToolTip(_translate("VariationSettingsWindow", "Fine tune the combinations of the modifiers"))
        self.btnConfigureCombinations.setText(_translate("VariationSettingsWindow", "Configure combinations..."))

